// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQwTxtiAXOIDLbEVFJElr8PJXawmNzmL0',
    appId: '1:937854044114:android:5d8d2b8a28d6751f8d2a0b',
    messagingSenderId: '937854044114',
    projectId: 'job-sync-5b0ad',
    storageBucket: 'job-sync-5b0ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSmmSOzBHEmfLDVbVPDFJrqkw80Z4Ijc',
    appId: '1:937854044114:ios:26665224665703678d2a0b',
    messagingSenderId: '937854044114',
    projectId: 'job-sync-5b0ad',
    storageBucket: 'job-sync-5b0ad.firebasestorage.app',
    iosBundleId: 'com.example.elitehire',
  );

}